exclude: ['vendor']
include: ['_pages']

title:            Rebel and Refuge
email:            rebelandrefuge@gmail.com
url:              http://www.rebelandrefuge.com
paginate:         5
paginate_path:    archive/page:num/
author:
  name:           Rebel and Refuge
  url:            http://www.rebelandrefuge.com
  email:          rebelandrefuge@gmail.com

# Site settings
description: > # this means to ignore newlines until "baseurl:"
  Become a Rebel. Find your refuge.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.rebelandrefuge.com" # the base hostname & protocol for your site
# twitter_username: twidx
# github_username:  tkwidmer

tag_page: '/blog/tags/'
category_page: '/blog/categories/'

collections:
  galleries:
    output: true

# Build settings
pages: ./_pages
markdown: kramdown

# pages_list:
#   Programming: '/pages/programming.html'
#   Speaking:   '/pages/speaking.html'
#   Blog: '/blog.html'
#   Feed: '/feed.xml'

# social_links:
#   - icon: fa-twitter
#     url: http://www.twitter.com/twidx
#   - icon: fa-github
#     url: http://www.github.com/tkwidmer

gems:
  - jekyll-redirect-from
